### ISSUE TITLE
Error:Execution failed for task ':app:ndkBuild'.

### ISSUE THREAD

**Issue by xiximeng** [enthusiasticgeek/Gstreamer_Android_Tutorials#1]
Error:Execution failed for task ':app:ndkBuild'.
> A problem occurred starting process 'command 'D:\android-sdk-windows\ndk-bundle/ndk-build.cmd''

I try many time, and it occure this problem. I search on the internet, but it cannot solve my problem , can you tell me why?
the only one different with you is i use win10, but you use ubuntu.

**Comment by enthusiasticgeek** [comment]
I am not sure how your environment is configured on windows. But did you try the following. Open a command window. Navigate to the directory of the project. Locate the program gradlew and type `./gradlew  tasks app:ndkLibsToJar app:ndkBuild app:assembleDebug --stacktrace` This will tell you exactly where the error occurred. Also I notice that your path has some front slashes (/) and some back slashes ( \ ). Can you confirm on Windows if mixing slashes for a path name is allowed?

**Comment by xiximeng** [comment]
Finally I solve this problem by removing the '-fuse-ld=gold' from 'path\to\GStreamer\root\arm64\share\gst-android\ndk-build\gstreamer-1.0.mk', I donnot know why, but it succeed!   Thank you very much!
